[package]
org = "savindusupun"
name = "eventure"
version = "0.1.0"
distribution = "2201.9.2"

# [[dependency]]
# org = "ballerinax"
# name = "postgresql"
# version = "1.12.0"

# [[dependency]]
# org = "ballerinax"
# name = "aws.s3"
# version = "0.1.0"

# [[dependency]]
# org = "exampleOrg"
# name = "exampleName"
# version = "0.1.0"

[build-options]
observabilityIncluded = true
